id: IBA338DDE
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:31:01.546721
last_modified: 2023-01-04 11:31:01.546732
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  75F2:
    title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site of
      Immortality'
    base_file: 75F2.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
